### ISSUE TITLE
I/O error when two identical notifications occur in a short period of time?

### ISSUE THREAD

**Issue by vcharpenay** [Hypermedea/ros2-binding#4]
```
[h] [ROS2Response] OK, Payload: json([kv(msg,[kv(data,true)]),kv(op,"publish"),kv(topic,"/obstacle")])
[h] [ROS2Response] OK, Payload: json([kv(msg,[kv(data,true)]),kv(op,"publish"),kv(topic,"/obstacle")])
[h] [ROS2PublishOperation] Method: PUT, Target: ros2+ws://localhost:9090/cmd_vel, Payload: json([kv("linear",[kv("x",0),kv("y",0),kv("z",0)]),kv("angular",[kv("x",0),kv("y",0),kv("z",0)])])
[h] [ROS2Response] OK, Payload: <none>
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at cartago.ArtifactOpMethod.exec(ArtifactOpMethod.java:39)
	at cartago.Artifact.doOperation(Artifact.java:447)
	at cartago.Artifact$ArtifactAdapter.doOperation(Artifact.java:1343)
	at cartago.Workspace.serveOperation(Workspace.java:1579)
	at cartago.Workspace$EnvironmentController.run(Workspace.java:1922)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: Output closed
	at org.hypermedea.ros.ROS2Operation.sendMessage(ROS2Operation.java:127)
	at org.hypermedea.ros.ROS2PublishOperation.sendSingleRequest(ROS2PublishOperation.java:39)
	at org.hypermedea.op.BaseOperation.sendRequest(BaseOperation.java:141)
	at org.hypermedea.HypermedeaArtifact.initiateOperation(HypermedeaArtifact.java:473)
	at org.hypermedea.HypermedeaArtifact.put(HypermedeaArtifact.java:319)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Output closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.hypermedea.ros.ROS2Operation.sendMessage(ROS2Operation.java:123)
	... 11 more
Caused by: java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.tryCompleteWrite(TransportImpl.java:619)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:557)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:192)
	... 12 more
[robot_controller] No failure event was generated for +!change_velocity(left)[code(put("ros2+ws://localhost:9090/cmd_vel",[json([kv("linear",[kv("x",0),kv("y",0),kv("z",0)]),kv("angular",[kv("x",0),kv("y",0),kv("z",0.5)])])],[kv("urn:hypermedea:ros2:messageType","geometry_msgs/msg/Twist")])),code_line(109),code_src("file:src/agt/robot_controller.asl"),env_failure_reason(operation_error("put/3")),error(action_failed),error_msg("Generic Error in Op execution"),source(self)]
intention 6: 
    +!change_velocity(left)[source(self)] <- ... put("ros2+ws://localhost:9090/cmd_vel",[json(V)],[kv("urn:hypermedea:ros2:messageType","geometry_msgs/msg/Twist")]) / {Direction=left, V=[kv("linear",[kv("x",0),kv("y",0),kv("z",0)]),kv("angular",[kv("x",0),kv("y",0),kv("z",0.5)])]}
    +!turn_left[source(self)] <- ... !change_velocity(left); .wait(T); !change_velocity(stop) / {T=2000}
    +json([kv(msg,[kv(data,true)]),kv(op,"publish"),kv(topic,"/obstacle")])[artifact_id(cobj_3),artifact_name(h),percept_type(obs_prop),source("ros2+ws://localhost:9090/text"),source(percept),workspace("/main/defi_ia_workspace",cobj_2)] <- ... !turn_left; !change_velocity(forward) / {Msg=[kv(msg,[kv(data,true)]),kv(op,"publish"),kv(topic,"/obstacle")], X=0.8820440540977963}

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at cartago.ArtifactOpMethod.exec(ArtifactOpMethod.java:39)
	at cartago.Artifact.doOperation(Artifact.java:447)
	at cartago.Artifact$ArtifactAdapter.doOperation(Artifact.java:1343)
	at cartago.Workspace.serveOperation(Workspace.java:1579)
	at cartago.Workspace$EnvironmentController.run(Workspace.java:1922)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: Output closed
	at org.hypermedea.ros.ROS2Operation.sendMessage(ROS2Operation.java:127)
	at org.hypermedea.ros.ROS2PublishOperation.sendSingleRequest(ROS2PublishOperation.java:39)
	at org.hypermedea.op.BaseOperation.sendRequest(BaseOperation.java:141)
	at org.hypermedea.HypermedeaArtifact.initiateOperation(HypermedeaArtifact.java:473)
	at org.hypermedea.HypermedeaArtifact.put(HypermedeaArtifact.java:319)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Output closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.hypermedea.ros.ROS2Operation.sendMessage(ROS2Operation.java:123)
	... 11 more
Caused by: java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.tryCompleteWrite(TransportImpl.java:619)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:557)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:192)
	... 12 more
[robot_controller] No failure event was generated for +!change_velocity(stop)[code(put("ros2+ws://localhost:9090/cmd_vel",[json([kv("linear",[kv("x",0),kv("y",0),kv("z",0)]),kv("angular",[kv("x",0),kv("y",0),kv("z",0)])])],[kv("urn:hypermedea:ros2:messageType","geometry_msgs/msg/Twist")])),code_line(109),code_src("file:src/agt/robot_controller.asl"),env_failure_reason(operation_error("put/3")),error(action_failed),error_msg("Generic Error in Op execution"),source(self)]
intention 7: 
    +!change_velocity(stop)[source(self)] <- ... put("ros2+ws://localhost:9090/cmd_vel",[json(V)],[kv("urn:hypermedea:ros2:messageType","geometry_msgs/msg/Twist")]) / {Direction=stop, V=[kv("linear",[kv("x",0),kv("y",0),kv("z",0)]),kv("angular",[kv("x",0),kv("y",0),kv("z",0)])]}
    +json([kv(msg,[kv(data,true)]),kv(op,"publish"),kv(topic,"/obstacle")])[artifact_id(cobj_3),artifact_name(h),percept_type(obs_prop),source("ros2+ws://localhost:9090/obstacle"),source(percept),workspace("/main/defi_ia_workspace",cobj_2)] <- ... !change_velocity(stop); .if_then_else((.random(X) & (X < 0.5)),!turn_right; !change_velocity(forward),!turn_left; !change_velocity(forward)) / {Msg=[kv(msg,[kv(data,true)]),kv(op,"publish"),kv(topic,"/obstacle")]}
```

**Comment by vcharpenay** [comment]
still occurring after 79a262d?
